# Generated by Django 4.0.3 on 2022-06-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_cursosytareas_entrega_cursosytareas_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadodelcurso',
            name='verificacion',
            field=models.CharField(choices=[('1', 'pendiente'), ('2', 'verificado'), ('3', 'inexistente')], default='pendiente', max_length=30),
        ),
    ]
