# Generated by Django 4.0.3 on 2022-06-17 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_estadodelcurso_verificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosytareas',
            name='entrega',
            field=models.DateField(default=datetime.date(2022, 6, 17)),
        ),
        migrations.AlterField(
            model_name='estadodelcurso',
            name='verificacion',
            field=models.CharField(default='pendiente', max_length=30),
        ),
    ]
