# Generated by Django 4.0.3 on 2022-06-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_cursosytareas_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursosytareas',
            name='anotacion',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
