# Generated by Django 4.0.3 on 2022-06-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_cursosytareas_anotacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosytareas',
            name='anotacion',
            field=models.CharField(default='Empty', max_length=1000),
        ),
    ]
