# Generated by Django 4.0.3 on 2022-06-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_alter_cursosytareas_anotacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosytareas',
            name='anotacion',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
