# Generated by Django 4.0.3 on 2022-06-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_cursosytareas_calificaion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursosytareas',
            name='calificado',
            field=models.BooleanField(default=False),
        ),
    ]
