# Generated by Django 4.0.3 on 2022-07-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_rename_calificaion_cursosytareas_calificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='usuario', max_length=100)),
                ('dashboardActivos', models.CharField(default='none', max_length=9999999)),
            ],
        ),
    ]
