# Generated by Django 4.0.3 on 2022-07-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para', models.CharField(default='usuario', max_length=100)),
                ('de', models.CharField(default='Anonimo', max_length=100)),
                ('asunto', models.CharField(default='Sin asunto', max_length=100)),
                ('contenido', models.TextField(blank=True, default='Mensjae vacío', max_length=9999999, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='settings',
            name='dashboardActivos',
            field=models.TextField(blank=True, default='none', max_length=9999999, null=True),
        ),
    ]
