# Generated by Django 4.0.3 on 2022-07-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_mensajes_alter_settings_dashboardactivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
