# Generated by Django 4.0.3 on 2022-07-16 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_mensajes_leido'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
