# Generated by Django 4.0.3 on 2022-07-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_mensajes_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='mensajeCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iamgen', models.ImageField(upload_to='fotos')),
            ],
        ),
    ]
