# Generated by Django 4.0.3 on 2022-07-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_mensajecorreo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mensajeCorreo',
        ),
    ]
