# Generated by Django 4.0.3 on 2022-07-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_delete_mensajecorreo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='dashboardActivos',
            field=models.TextField(blank=True, default='', max_length=9999999, null=True),
        ),
    ]
